version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: orm-playground
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 5435:5432